/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ServicesSalesforceConsultingRouteImport } from './routes/Services- Salesforce Consulting'
import { Route as PartnershipRouteImport } from './routes/Partnership'
import { Route as Asteri_productSuiteRouteImport } from './routes/Asteri_product-suite'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesSoftwareDevelopmentRouteImport } from './routes/services/software-development'
import { Route as ServicesSapConsultingRouteImport } from './routes/services/sap-consulting'
import { Route as ServicesDataScienceRouteImport } from './routes/services/data-science'
import { Route as ServicesCloudSolutionsRouteImport } from './routes/services/cloud-solutions'

const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSalesforceConsultingRoute =
  ServicesSalesforceConsultingRouteImport.update({
    id: '/Services- Salesforce Consulting',
    path: '/Services- Salesforce Consulting',
    getParentRoute: () => rootRouteImport,
  } as any)
const PartnershipRoute = PartnershipRouteImport.update({
  id: '/Partnership',
  path: '/Partnership',
  getParentRoute: () => rootRouteImport,
} as any)
const Asteri_productSuiteRoute = Asteri_productSuiteRouteImport.update({
  id: '/Asteri_product-suite',
  path: '/Asteri_product-suite',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSoftwareDevelopmentRoute =
  ServicesSoftwareDevelopmentRouteImport.update({
    id: '/software-development',
    path: '/software-development',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesSapConsultingRoute = ServicesSapConsultingRouteImport.update({
  id: '/sap-consulting',
  path: '/sap-consulting',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesDataScienceRoute = ServicesDataScienceRouteImport.update({
  id: '/data-science',
  path: '/data-science',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesCloudSolutionsRoute = ServicesCloudSolutionsRouteImport.update({
  id: '/cloud-solutions',
  path: '/cloud-solutions',
  getParentRoute: () => ServicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Asteri_product-suite': typeof Asteri_productSuiteRoute
  '/Partnership': typeof PartnershipRoute
  '/Services- Salesforce Consulting': typeof ServicesSalesforceConsultingRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/products': typeof ProductsRoute
  '/services': typeof ServicesRouteWithChildren
  '/solutions': typeof SolutionsRoute
  '/services/cloud-solutions': typeof ServicesCloudSolutionsRoute
  '/services/data-science': typeof ServicesDataScienceRoute
  '/services/sap-consulting': typeof ServicesSapConsultingRoute
  '/services/software-development': typeof ServicesSoftwareDevelopmentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Asteri_product-suite': typeof Asteri_productSuiteRoute
  '/Partnership': typeof PartnershipRoute
  '/Services- Salesforce Consulting': typeof ServicesSalesforceConsultingRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/products': typeof ProductsRoute
  '/services': typeof ServicesRouteWithChildren
  '/solutions': typeof SolutionsRoute
  '/services/cloud-solutions': typeof ServicesCloudSolutionsRoute
  '/services/data-science': typeof ServicesDataScienceRoute
  '/services/sap-consulting': typeof ServicesSapConsultingRoute
  '/services/software-development': typeof ServicesSoftwareDevelopmentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Asteri_product-suite': typeof Asteri_productSuiteRoute
  '/Partnership': typeof PartnershipRoute
  '/Services- Salesforce Consulting': typeof ServicesSalesforceConsultingRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/products': typeof ProductsRoute
  '/services': typeof ServicesRouteWithChildren
  '/solutions': typeof SolutionsRoute
  '/services/cloud-solutions': typeof ServicesCloudSolutionsRoute
  '/services/data-science': typeof ServicesDataScienceRoute
  '/services/sap-consulting': typeof ServicesSapConsultingRoute
  '/services/software-development': typeof ServicesSoftwareDevelopmentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Asteri_product-suite'
    | '/Partnership'
    | '/Services- Salesforce Consulting'
    | '/about'
    | '/blog'
    | '/case-studies'
    | '/contact'
    | '/industries'
    | '/products'
    | '/services'
    | '/solutions'
    | '/services/cloud-solutions'
    | '/services/data-science'
    | '/services/sap-consulting'
    | '/services/software-development'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Asteri_product-suite'
    | '/Partnership'
    | '/Services- Salesforce Consulting'
    | '/about'
    | '/blog'
    | '/case-studies'
    | '/contact'
    | '/industries'
    | '/products'
    | '/services'
    | '/solutions'
    | '/services/cloud-solutions'
    | '/services/data-science'
    | '/services/sap-consulting'
    | '/services/software-development'
  id:
    | '__root__'
    | '/'
    | '/Asteri_product-suite'
    | '/Partnership'
    | '/Services- Salesforce Consulting'
    | '/about'
    | '/blog'
    | '/case-studies'
    | '/contact'
    | '/industries'
    | '/products'
    | '/services'
    | '/solutions'
    | '/services/cloud-solutions'
    | '/services/data-science'
    | '/services/sap-consulting'
    | '/services/software-development'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Asteri_productSuiteRoute: typeof Asteri_productSuiteRoute
  PartnershipRoute: typeof PartnershipRoute
  ServicesSalesforceConsultingRoute: typeof ServicesSalesforceConsultingRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  CaseStudiesRoute: typeof CaseStudiesRoute
  ContactRoute: typeof ContactRoute
  IndustriesRoute: typeof IndustriesRoute
  ProductsRoute: typeof ProductsRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SolutionsRoute: typeof SolutionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Services- Salesforce Consulting': {
      id: '/Services- Salesforce Consulting'
      path: '/Services- Salesforce Consulting'
      fullPath: '/Services- Salesforce Consulting'
      preLoaderRoute: typeof ServicesSalesforceConsultingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Partnership': {
      id: '/Partnership'
      path: '/Partnership'
      fullPath: '/Partnership'
      preLoaderRoute: typeof PartnershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Asteri_product-suite': {
      id: '/Asteri_product-suite'
      path: '/Asteri_product-suite'
      fullPath: '/Asteri_product-suite'
      preLoaderRoute: typeof Asteri_productSuiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/software-development': {
      id: '/services/software-development'
      path: '/software-development'
      fullPath: '/services/software-development'
      preLoaderRoute: typeof ServicesSoftwareDevelopmentRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/sap-consulting': {
      id: '/services/sap-consulting'
      path: '/sap-consulting'
      fullPath: '/services/sap-consulting'
      preLoaderRoute: typeof ServicesSapConsultingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/data-science': {
      id: '/services/data-science'
      path: '/data-science'
      fullPath: '/services/data-science'
      preLoaderRoute: typeof ServicesDataScienceRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/cloud-solutions': {
      id: '/services/cloud-solutions'
      path: '/cloud-solutions'
      fullPath: '/services/cloud-solutions'
      preLoaderRoute: typeof ServicesCloudSolutionsRouteImport
      parentRoute: typeof ServicesRoute
    }
  }
}

interface ServicesRouteChildren {
  ServicesCloudSolutionsRoute: typeof ServicesCloudSolutionsRoute
  ServicesDataScienceRoute: typeof ServicesDataScienceRoute
  ServicesSapConsultingRoute: typeof ServicesSapConsultingRoute
  ServicesSoftwareDevelopmentRoute: typeof ServicesSoftwareDevelopmentRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesCloudSolutionsRoute: ServicesCloudSolutionsRoute,
  ServicesDataScienceRoute: ServicesDataScienceRoute,
  ServicesSapConsultingRoute: ServicesSapConsultingRoute,
  ServicesSoftwareDevelopmentRoute: ServicesSoftwareDevelopmentRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Asteri_productSuiteRoute: Asteri_productSuiteRoute,
  PartnershipRoute: PartnershipRoute,
  ServicesSalesforceConsultingRoute: ServicesSalesforceConsultingRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  CaseStudiesRoute: CaseStudiesRoute,
  ContactRoute: ContactRoute,
  IndustriesRoute: IndustriesRoute,
  ProductsRoute: ProductsRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SolutionsRoute: SolutionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
